AWSTemplateFormatVersion: "2010-09-09"
Description: YAML EXAMPLE sample template
Resources:
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0ff8a91507f77f867" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: testkey
      BlockDeviceMappings:
        -
          DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 20
      Tags:
        - Key: yor_trace
          Value: 68f32cca-cac4-4b46-b502-e63cbda9e8c9





